POST http://localhost:8080/users/register
Content-Type: application/json

{ "name": "Tamu Baru", "email": "tamu@gmail.com", "password": "password123" , "role" : "admin"}

###
# @name loginRequest
POST http://localhost:8080/users/login
Content-Type: application/json

{"email": "tamu@gmail.com", "password": "password123" }

###
@authToken = {{loginRequest.response.body.result.token}}
GET http://localhost:8080/users
Authorization: Bearer {{authToken}}

###
@authToken = {{loginRequest.response.body.result.token}}
GET http://localhost:8080/users/u-7821-abc-99
Authorization: Bearer {{authToken}}

###
@authToken = {{loginRequest.response.body.result.token}}

PUT http://localhost:8080/users/u-7821-abc-99
Authorization: Bearer {{authToken}}

{"email": "tamu@gma", "password": "password123" }