POST http://localhost:8080/users/register
Content-Type: application/json

{ "name": "Tamu Baru", "email": "tamu@gmail.com", "password": "password123" , "role" : "admin"}

###
# @name loginRequest
POST http://localhost:8080/users/login
Content-Type: application/json

{"email": "tamu@gmail.com", "password": "password123" }

###
@authToken = {{loginRequest.response.body.result.token}}
GET http://localhost:8080/users
Authorization: Bearer {{authToken}}

###
@myId = {{loginRequest.response.body.result.id}}
GET http://localhost:8080/users/{{myId}}
Authorization: Bearer {{authToken}}

###
PUT http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{"email": "budi@co.id","name" : "Budi", "password": "pass1212", "role" : "admin" }

###

DELETE http://localhost:8080/users/me
Authorization: Bearer {{authToken}}
